version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_scheduling
    restart: always
    environment:
      POSTGRES_DB: scheduling
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5253:5432"

  api:
    build: .
    container_name: scheduling_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/scheduling
      DB_USER: admin
      DB_PASSWORD: secret
